mutation GITHUB_LOGIN($code: String!) {
  auth: github_login(code: $code) {
    token
  }
}

mutation LOCAL_LOGIN($userId: String!, $password: String!) {
  auth: local_login(user_id: $userId, password: $password) {
    token
  }
}
