import {
  GET_NOTIFICATION_LIST,
  GET_MENTION_NOTIFICATION_LIST,
  GET_NOTIFICATION_COUNT,
} from './getNotification.gql';
import { CONFIRM_NOTIFICATION } from './modifyNotification.gql';

export {
  GET_NOTIFICATION_LIST,
  GET_MENTION_NOTIFICATION_LIST,
  GET_NOTIFICATION_COUNT,
  CONFIRM_NOTIFICATION,
};
