import { ADD_BASIC_TWEET, ADD_REPLY_TWEET, ADD_RETWEET } from './addTweet.gql';
import {
  GET_TWEETLIST,
  GET_USER_TWEETLIST,
  GET_USER_ALL_TWEETLIST,
  GET_TWEET_DETAIL,
  GET_CHILD_TWEETLIST,
  GET_SEARCH_TWEETLIST,
  GET_HEART_TWEETLIST,
} from './getTweet.gql';
import { DELETE_TWEET } from './deleteTweet.gql';
import { HEART_TWEET, UNHEART_TWEET } from './modifyTweet.gql';

export {
  ADD_BASIC_TWEET,
  ADD_REPLY_TWEET,
  ADD_RETWEET,
  GET_TWEETLIST,
  GET_USER_TWEETLIST,
  GET_USER_ALL_TWEETLIST,
  GET_TWEET_DETAIL,
  GET_CHILD_TWEETLIST,
  GET_SEARCH_TWEETLIST,
  GET_HEART_TWEETLIST,
  DELETE_TWEET,
  HEART_TWEET,
  UNHEART_TWEET,
};
