type Notification {
  user: User
  tweet: Tweet
  type: String
  is_read: Boolean
  createAt: Date
}
type Count {
  count: Int
}

type Query {
  notification_count: Count
  notification: [Notification]
}

type Mutation {
  update_notification: Response
}
