type Notification {
  giver: User
  user_id: String
  tweet: Tweet
  type: String
  _id: String
  createAt: Date
}
type Count {
  count: Int
}

type Query {
  notification_count(lastest_notification_id: String): Count
  notification_list(oldest_notification_id: String): [Notification]
  notification_mention_list(oldest_notification_id: String): [Notification]
}

type Mutation {
  update_notification(id: String): Response
}
