type Tweet {
  _id: String
  author_id: String
  author: User
  content: String
  img_url_list: [String]
  parent_id: String
  retweet_id: String
  retweet: Tweet
  child_tweet_number: Int
  child_tweet_list: [Tweet]
  retweet_user_number: Int
  heart_user_number: Int
  createAt: Date
}

type Query {
  following_tweet_list(oldest_tweet_id: String): [Tweet]
  user_tweet_list(user_id: String, oldest_tweet_id: String): [Tweet]
  user_all_tweet_list(user_id: String, oldest_tweet_id: String): [Tweet]
  child_tweet_list(tweet_id: String!, oldest_tweet_id: String): [Tweet]
  detail_tweet(tweet_id: String!): Tweet
  heart_tweet_list(user_id: String!, oldest_tweet_id: String): [Tweet]
  search_tweet_list(search_word: String!, oldest_tweet_id: String): [Tweet]
  latest_tweet_list(latest_tweet_id: String): [Tweet]
}

type Mutation {
  add_basic_tweet(content: String!, img_url_list: [String]): Tweet
  add_reply_tweet(content: String!, img_url_list: [String], parent_id: String!): Tweet
  add_retweet(content: String, retweet_id: String!): Tweet
  delete_tweet(tweet_id: String!): Response
  heart_tweet(tweet_id: String!): Tweet
  unheart_tweet(tweet_id: String!): Tweet
}
