type User {
  _id: String
  user_id: String
  name: String
  profile_img_url: String
  comment: String
  background_img_url: String
  following_id_list: [String]
}
type Auth {
  token: String
}
type Query {
  following_list(user_id: String, oldest_user_id: String): [User]
  follower_list(user_id: String, oldest_user_id: String): [User]
  heart_user_list(tweet_id: String, oldest_user_id: String): [User]
  retweet_user_list(tweet_id: String, oldest_user_id: String): [User]
  search_user_list(search_word: String!, oldest_user_id: String): [User]
  my_info: User
  user_info(user_id: String): User
}

type Mutation {
  github_login(code: String!): Auth
  create_user(user_id: String!, name: String!, password: String!): Response
  local_login(user_id: String!, password: String!): Auth
  update_user_name(name: String!): Response
  follow_user(follow_user_id: String!): User
  unfollow_user(unfollow_user_id: String!): User
}
