import { ADD_USER } from './addUser.gql';
import {
  GET_MYINFO,
  GET_USER_DETAIL,
  GET_FOLLOWER_LIST,
  GET_FOLLOWING_LIST,
  GET_SEARCH_USERLIST,
  GET_HEART_USERLIST,
  GET_RETWEET_USERLIST,
} from './getUser.gql';
import { FOLLOW_USER, UNFOLLOW_USER, UPDATE_USER_INFO } from './modifyUser.gql';

export {
  ADD_USER,
  GET_MYINFO,
  GET_USER_DETAIL,
  GET_FOLLOWER_LIST,
  GET_FOLLOWING_LIST,
  GET_SEARCH_USERLIST,
  GET_HEART_USERLIST,
  GET_RETWEET_USERLIST,
  FOLLOW_USER,
  UNFOLLOW_USER,
  UPDATE_USER_INFO,
};
