mutation FOLLOW_USER($follow_user_id: String!) {
  user: follow_user(follow_user_id: $follow_user_id) {
    user_id
  }
}

mutation UNFOLLOW_USER($unfollow_user_id: String!) {
  user: unfollow_user(unfollow_user_id: $unfollow_user_id) {
    user_id
  }
}
