query($tweetId: String!, $oldestTweetId: String) {
  tweetList: child_tweet_list(tweet_id: $tweetId, oldest_tweet_id: $oldestTweetId) {
    _id
    content
    child_tweet_number
    retweet_user_number
    heart_user_number
    author {
      user_id
      name
      profile_img_url
    }
  }
}
