query {
  notifications: notification_mention_list {
    giver {
      user_id
      profile_img_url
    }
    tweet {
      content
      author {
        user_id
        profile_img_url
      }
    }
    type
    _id
  }
}
