query($userId: String) {
  user: user_info(user_id: $userId) {
    user_id
    name
    comment
    profile_img_url
    background_img_url
  }
  followerList: follower_list(user_id: $userId) {
    user_id
    name
    comment
    profile_img_url
  }
  followingList: following_list(user_id: $userId) {
    user_id
    name
    comment
    profile_img_url
  }
}
