query($userId: String, $oldestTweetId: String) {
  tweetList: user_tweet_list(user_id: $userId, oldest_tweet_id: $oldestTweetId) {
    _id
    content
    child_tweet_number
    retweet_user_number
    heart_user_number
    img_url_list
    retweet {
      _id
      content
      child_tweet_number
      retweet_user_number
      heart_user_number
      img_url_list
      author {
        user_id
        name
        profile_img_url
      }
    }
    author {
      user_id
      name
      profile_img_url
    }
  }
}
